### ISSUE TITLE
Add feedback when target zip upload fails

### ISSUE THREAD

**Issue by hobinjk-ptc** [ptcrealitylab/vuforia-spatial-edge-server#123]
https://forum.spatialtoolbox.vuforia.com/t/when-i-upload-the-zip-for-an-object-target-nothing-happens/46

**Comment by realityLabDiscourseUser** [comment]
This issue has been mentioned on **Vuforia Spatial Toolbox Community**. There might be relevant details there:

https://forum.spatialtoolbox.vuforia.com/t/when-i-upload-the-zip-for-an-object-target-nothing-happens/46/6

**Comment by benptc** [comment]
I'm halfway done with a new feature that adds a notification feature where errors and user-facing messages can pop up at the top of the web interface for a few seconds

**Comment by realityLabDiscourseUser** [comment]
This issue has been mentioned on **Vuforia Spatial Toolbox Community**. There might be relevant details there:

https://forum.spatialtoolbox.vuforia.com/t/when-i-upload-the-zip-for-an-object-target-nothing-happens/46/7
