### ISSUE TITLE
node-rest-client is not maintained

### ISSUE THREAD

**Issue by valentinptc** [ptcrealitylab/vuforia-spatial-edge-server#127]
The world seemed to move on to: https://github.com/axios/axios

we should implement this instead, since node-rest-client is not maintained since 3 years

**Comment by hobinjk-ptc** [comment]
I personally prefer node-fetch which implements the [browser fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API)

**Comment by valentinptc** [comment]
solved
