### ISSUE TITLE
Fix Dockerfile

### ISSUE THREAD

**Issue by hobinjk-ptc** [ptcrealitylab/vuforia-spatial-edge-server#200]
As currently written the Dockerfile appears to just clone the existing app directory which won't work unless it's already a fully set up server which negates the purpose of the Dockerfile.

The file would be better implemented as https://github.com/bouviervj/vuforia-spatial-edge-server/blob/master/Dockerfile which performs the necessary setup steps.

**Comment by valentinptc** [comment]
I agree to git clone for a stand alone docker file. We can add that. However for development there is value in the presented method.

https://github.com/bouviervj/vuforia-spatial-edge-server/blob/master/Dockerfile is missing 

```
EXPOSE 49368
EXPOSE 52316
```

`mkdir -p /tmp/Documents` is no longer required

and `FROM ubuntu:18.04` is better replaced with `FROM node:12` (not every deployment and test environment is ubuntu 18.04.

**Comment by hobinjk-ptc** [comment]
This issue was mostly about the use of `COPY` since it's flawed here and not flawed in the earlier dockerfile. I agree that the node:12 base image is better.

**Comment by hobinjk-ptc** [comment]
Fixed in 62e5c51
